In [26]:
import numpy as np
import pandas as pd

In [27]:
x=[1,2,3,5,1,2]
nx=np.array(x)

In [28]:
print(nx)

[1 2 3 5 1 2]


In [29]:
print(nx.shape)

(6,)


In [30]:
ny=np.array([[1,2,3],[4,5,6]])
print(ny.shape)

(2, 3)


In [31]:
one=np.arange(1,100,.2)

In [32]:
one.shape

(495,)

In [33]:
print(one.size)

495


In [61]:
two=np.linspace(1,100,200)
two

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [35]:
n3=np.random.rand(100)
n3

array([0.44110664, 0.86242983, 0.83826499, 0.67602577, 0.60590454,
       0.92069953, 0.80619834, 0.83706467, 0.58767778, 0.76997483,
       0.18617671, 0.56525355, 0.78006862, 0.8441782 , 0.97486012,
       0.32552188, 0.93372495, 0.99481678, 0.38635303, 0.15698183,
       0.52155244, 0.52778648, 0.23918616, 0.65178566, 0.65138987,
       0.69675923, 0.17601928, 0.69282118, 0.2154644 , 0.48284286,
       0.41297227, 0.08159959, 0.21543637, 0.40624839, 0.23886558,
       0.70001621, 0.43817941, 0.63467514, 0.92812319, 0.80982177,
       0.22050379, 0.96591235, 0.2350715 , 0.42433433, 0.23636283,
       0.22326224, 0.33788721, 0.10778402, 0.93443545, 0.96326198,
       0.29023611, 0.81258798, 0.80896723, 0.86083971, 0.2849765 ,
       0.59046649, 0.23794586, 0.55067428, 0.17133546, 0.99825174,
       0.86136019, 0.89485527, 0.33242828, 0.68921543, 0.964626  ,
       0.79283671, 0.24554263, 0.12486116, 0.01634079, 0.64621343,
       0.1817745 , 0.52821922, 0.69210678, 0.12037056, 0.10091

In [36]:
print (n3.size)

100


In [37]:
# 100 times data with range between 1 to 10
n4=np.random.randint(1,10,100)
n4

array([7, 1, 9, 8, 7, 7, 5, 6, 4, 8, 2, 4, 8, 7, 4, 8, 2, 5, 5, 1, 9, 6,
       1, 5, 5, 2, 7, 1, 1, 9, 7, 9, 4, 7, 4, 5, 5, 4, 5, 9, 2, 3, 6, 4,
       6, 5, 6, 7, 5, 3, 6, 2, 8, 5, 5, 8, 4, 4, 9, 1, 5, 1, 2, 1, 5, 1,
       4, 2, 6, 5, 3, 7, 2, 1, 4, 6, 6, 9, 5, 4, 9, 5, 7, 7, 4, 9, 6, 6,
       2, 5, 1, 2, 7, 1, 6, 4, 9, 6, 5, 7])

In [38]:
n4.reshape((10,10))

array([[7, 1, 9, 8, 7, 7, 5, 6, 4, 8],
       [2, 4, 8, 7, 4, 8, 2, 5, 5, 1],
       [9, 6, 1, 5, 5, 2, 7, 1, 1, 9],
       [7, 9, 4, 7, 4, 5, 5, 4, 5, 9],
       [2, 3, 6, 4, 6, 5, 6, 7, 5, 3],
       [6, 2, 8, 5, 5, 8, 4, 4, 9, 1],
       [5, 1, 2, 1, 5, 1, 4, 2, 6, 5],
       [3, 7, 2, 1, 4, 6, 6, 9, 5, 4],
       [9, 5, 7, 7, 4, 9, 6, 6, 2, 5],
       [1, 2, 7, 1, 6, 4, 9, 6, 5, 7]])

In [39]:
n4.reshape((10,5,2))

array([[[7, 1],
        [9, 8],
        [7, 7],
        [5, 6],
        [4, 8]],

       [[2, 4],
        [8, 7],
        [4, 8],
        [2, 5],
        [5, 1]],

       [[9, 6],
        [1, 5],
        [5, 2],
        [7, 1],
        [1, 9]],

       [[7, 9],
        [4, 7],
        [4, 5],
        [5, 4],
        [5, 9]],

       [[2, 3],
        [6, 4],
        [6, 5],
        [6, 7],
        [5, 3]],

       [[6, 2],
        [8, 5],
        [5, 8],
        [4, 4],
        [9, 1]],

       [[5, 1],
        [2, 1],
        [5, 1],
        [4, 2],
        [6, 5]],

       [[3, 7],
        [2, 1],
        [4, 6],
        [6, 9],
        [5, 4]],

       [[9, 5],
        [7, 7],
        [4, 9],
        [6, 6],
        [2, 5]],

       [[1, 2],
        [7, 1],
        [6, 4],
        [9, 6],
        [5, 7]]])

In [40]:
n5=n4.reshape((25,4))

In [41]:
n1=np.random.randint(1,10,(5,5))
n2=np.random.randint(1,10,(5,5))

In [42]:
n1

array([[9, 9, 6, 9, 3],
       [5, 5, 3, 5, 5],
       [9, 9, 1, 2, 6],
       [1, 7, 8, 3, 1],
       [6, 3, 6, 4, 9]])

In [43]:
n1/n2

array([[3.        , 1.8       , 0.85714286, 1.28571429, 0.375     ],
       [0.71428571, 0.625     , 0.375     , 5.        , 2.5       ],
       [1.8       , 1.125     , 0.14285714, 0.28571429, 0.75      ],
       [0.16666667, 7.        , 8.        , 1.5       , 0.33333333],
       [1.2       , 0.6       , 1.        , 0.66666667, 3.        ]])

In [44]:
n1-n2

array([[ 6,  4, -1,  2, -5],
       [-2, -3, -5,  4,  3],
       [ 4,  1, -6, -5, -2],
       [-5,  6,  7,  1, -2],
       [ 1, -2,  0, -2,  6]])

In [45]:
n1+n2

array([[12, 14, 13, 16, 11],
       [12, 13, 11,  6,  7],
       [14, 17,  8,  9, 14],
       [ 7,  8,  9,  5,  4],
       [11,  8, 12, 10, 12]])

In [46]:
n1**4

array([[6561, 6561, 1296, 6561,   81],
       [ 625,  625,   81,  625,  625],
       [6561, 6561,    1,   16, 1296],
       [   1, 2401, 4096,   81,    1],
       [1296,   81, 1296,  256, 6561]], dtype=int32)

In [47]:
# //multiplication of matrix
n1.dot(n2)

array([[189, 189, 204, 150, 174],
       [120, 119, 131, 101, 104],
       [137, 157, 180, 119, 122],
       [115, 133, 128,  82,  98],
       [138, 151, 166, 149, 141]])

In [48]:
n2

array([[3, 5, 7, 7, 8],
       [7, 8, 8, 1, 2],
       [5, 8, 7, 7, 8],
       [6, 1, 1, 2, 3],
       [5, 5, 6, 6, 3]])

In [49]:
n1*n2

array([[27, 45, 42, 63, 24],
       [35, 40, 24,  5, 10],
       [45, 72,  7, 14, 48],
       [ 6,  7,  8,  6,  3],
       [30, 15, 36, 24, 27]])

In [50]:
n1+10

array([[19, 19, 16, 19, 13],
       [15, 15, 13, 15, 15],
       [19, 19, 11, 12, 16],
       [11, 17, 18, 13, 11],
       [16, 13, 16, 14, 19]])

In [51]:
n6=np.random.randint(1,10,10)

In [52]:
n7=np.random.randint(1,10,(3,4))

In [53]:
n7

array([[3, 6, 1, 2],
       [6, 7, 5, 6],
       [5, 2, 8, 3]])

In [54]:
print(n7[0])
print(n7[-1])
print(n7[:,0])
print(n7[:,1])
# print(n7[1:3])
print(n7[0:2,1:3])

[3 6 1 2]
[5 2 8 3]
[3 6 5]
[6 7 2]
[[6 1]
 [7 5]]


In [55]:
n7

array([[3, 6, 1, 2],
       [6, 7, 5, 6],
       [5, 2, 8, 3]])

In [56]:
#flatten a n dimension to 1 dimension matrix
n7.flatten()

array([3, 6, 1, 2, 6, 7, 5, 6, 5, 2, 8, 3])

In [57]:
#flatten a n dimension to 1 dimension matrix
n7.ravel()

array([3, 6, 1, 2, 6, 7, 5, 6, 5, 2, 8, 3])

In [58]:
n7.T

array([[3, 6, 5],
       [6, 7, 2],
       [1, 5, 8],
       [2, 6, 3]])

In [59]:
n7.transpose()

array([[3, 6, 5],
       [6, 7, 2],
       [1, 5, 8],
       [2, 6, 3]])

In [62]:
#to find the maximum
n7.max()


8

In [67]:
n7.mean()

4.5

In [63]:
#to find the minimum
n7.min()

1

In [64]:
#sum of all the values
n7.sum()

54

In [65]:
#sum of all values in each column
n7.sum(axis=0)

array([14, 15, 14, 11])

In [66]:
#sum of all values in each row
n7.sum(axis=1)

array([12, 24, 18])

In [70]:
#tells us the number of rows and col
n5.shape


(25, 4)

In [76]:

#maximum value along with its index
print(n7,"\n",n7.max(),"found at ",n7.argmax())

[[3 6 1 2]
 [6 7 5 6]
 [5 2 8 3]] 
 8 found at  10


In [78]:
print(n7,"\n",n7.min(),"found at ",n7.argmin())

[[3 6 1 2]
 [6 7 5 6]
 [5 2 8 3]] 
 1 found at  2


In [79]:
a=np.random.randint(1,100,(3,2))
b=np.random.randint(1,100,(3,2))
c=np.random.randint(1,100,(2,3))
print(a)
print(b)
print(c)


[[ 4 61]
 [11 94]
 [35 36]]
[[26 28]
 [40 65]
 [ 7 40]]
[[41 27 87]
 [90 35 27]]


In [80]:
np.hstack((a,b)) #join horizontally

array([[ 4, 61, 26, 28],
       [11, 94, 40, 65],
       [35, 36,  7, 40]])

In [81]:
np.vstack((a,b)) #join vetically

array([[ 4, 61],
       [11, 94],
       [35, 36],
       [26, 28],
       [40, 65],
       [ 7, 40]])

In [82]:
np.vstack((a,c.T))

array([[ 4, 61],
       [11, 94],
       [35, 36],
       [41, 90],
       [27, 35],
       [87, 27]])

In [84]:
m=np.array([1,2,3,4,56,78,765,43,22,346,654,2,4,6,65,78,8,89,9,5,4,34])

In [85]:
#boolean filter
m>5

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True, False, False,  True])

In [86]:
m[m>5]

array([ 56,  78, 765,  43,  22, 346, 654,   6,  65,  78,   8,  89,   9,
        34])

In [87]:
m[m!=2]

array([  1,   3,   4,  56,  78, 765,  43,  22, 346, 654,   4,   6,  65,
        78,   8,  89,   9,   5,   4,  34])

In [88]:
m[(m>2) &(m<8)]

array([3, 4, 4, 6, 5, 4])

In [92]:
mat=[]
for i in range(10):
    mat.append(int(input('enter Value')))
mat=np.array(mat)

In [93]:
print(mat,mat.shape)

[  1 223  34   5  67 788   9   0   6  45] (10,)


In [94]:
mat=[]
for i in range(2):
    smat=[]
    smat.append(int(input('enter Value')))
    mat.append(smat)
mat=np.array(mat)
print(mat,mat.shape)

[[2]
 [3]] (2, 1)
